### PR TITLE
Port UT_LIST from innodb 8.x

### PR DESCRIPTION
**Pull request by RahulKushwaha**
**Background**: Port UT_LIST from innodb 8.x

**Tests**: 

- ib_cfg: **_NA_**
- ib_cursor: Success
- ib_ddl: Success
- ib_deadlock: **_Failing_**
- ib_dict: Success
- ib_drop: Success
- ib_index: Success
- ib_logger: Success
- ib_mt_drv: Success
- ib_mt_stress: **_NA_**
- ib_perf1: Success
- ib_recover: Success
- ib_search: Success
- ib_shutdown: Success
- ib_status: Success
- ib_tablename: Success
- ib_test1: Success
- ib_test2: Success
- ib_test3: Success
- ib_test5: Success
- ib_types: Success
- ib_update: Success

### CODE REVIEW

**Comment by RahulKushwaha** [comment]
@sunbains Added one more commit `Fix sym_list`, and now majority of the tests are passing. `ib_ddl` and `ib_deadlock` are failing. I will dig more.

**Comment by sunbains** [comment]
Interesting, they passed for me in the ut_list branch.

**Comment by RahulKushwaha** [comment]
Fixed `ib_ddl`. 

`id_deadlock` gives error on the ut_list branch as well. 
error 
``` void *worker_thread(void *): Assertion `err == DB_SUCCESS || err == DB_DEADLOCK || err == DB_LOCK_WAIT_TIMEOUT' failed.```

**Comment by RahulKushwaha** [comment]
I tried running on `main`, `ut_list`. `ib_deadlock` fails for me. 
The error is on the assertion 
```
      err = insert_rows(crsr2, 0, n_rows, thread_id);
      assert(err == DB_SUCCESS || err == DB_DEADLOCK ||
             err == DB_LOCK_WAIT_TIMEOUT);
             ```
Instead err = DB_DUPLICATE_KEY

**Comment by subains** [comment]
If it fails in main then please add that to the comment when you merge it.

Don't bother fixing it. The lock manager will get a shakeout when we write unit tests.

**Comment by RahulKushwaha** [comment]
Sure. I will put that as the message of the merge(squash) commit. 
(btw I don't have permissions to add you as the reviewer or merge this PR as well)

**Comment by sunbains** [comment]
Thank you.

**Comment by sunbains** [comment]
I need to figure out how to give you permission to merge PRs. Give me a day or two.

**Pull request merged**
